# docker-compose.yml
services:
  react-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-react
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true
    init: true
    networks:
      - react-network

networks:
  react-network:
    driver: bridge